---
es_home: "{{ es_user_home }}/usr/share/elasticsearch"
es_version: "5.6.3"
es_major_version: "{{ es_version[0:1] }}.x"
es_version_lock: false
es_use_repository: true
es_repo: "http://repo/repo6/hadoop/ELS/centos6/{{ es_major_version }}/{{ es_version }}/"
es_yum_key: "http://repo/repo6/hadoop/ELS/centos6/{{ es_major_version }}/{{ es_version }}/RPM-GPG-KEY/GPG-KEY-elasticsearch"
es_apt_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
es_apt_url: "deb https://artifacts.elastic.co/packages/{{ es_major_version }}/apt stable main"
es_apt_url_old: "deb http://packages.elastic.co/elasticsearch/{{ es_major_version }}/debian stable main"
es_start_service: true
es_java_install: true
update_java: false
es_restart_on_change: true
es_plugins_reinstall: false
es_scripts: false
es_templates: false

es_user: bgd_elasticsearch1
es_group: elasticsearch
es_tarball: "elasticsearch-{{ es_version }}.tar.gz"

es_user_home: "/appl/{{ es_user }}"

es_config: {}

flume_agents: "flume-assemblage-lille-s1, flume-assemblage-lille-s2"

#Need to provide default directories
es_instance_name: "{{ es_user }}"
es_conf_dir: "{{ es_user_home }}/etc/elasticsearch"
es_pid_dir: "{{ es_user_home }}/var/run/elasticsearch"
es_log_dir: "{{ es_user_home }}/var/log/elasticsearch"
es_data_dirs: "/DATA1/elasticsearch,/DATA2/elasticsearch,/DATA3/elasticsearch,/DATA4/elasticsearch,/DATA5/elasticsearch,/DATA6/elasticsearch"
es_max_open_files: 65536
es_max_map_count: 262144
es_allow_downgrades: false
es_enable_xpack: false
es_xpack_features: ["alerting","monitoring","graph","security"]
#These are used for internal operations performed by ansible.
#They do not effect the current configuration
es_api_host: "{{ inventory_hostname }}"
es_api_port: 9200

# Since ansible 2.2 the following variables need to be defined
# to allow the role to be conditionally played with a when condition.
pid_dir: ''
log_dir: ''
conf_dir: ''
data_dirs: ''
# JVM custom parameters
es_jvm_custom_parameters: ''

#Plugins
#ReadOnlyRest Plugins
readonlyrest_version: "1.16.14"
readonlyrest_tarball: "readonlyrest-{{ es_version }}.zip"
install_readonlyrest: false

#Supervision
nagios_user: "nagiosuser"
nagios_group: "nagios"

#Tools
admin_tools_home: "/appl/{{ curator_user }}/admin_tools"

#Curator
curator_home: "{{ admin_tools_home }}/curator"
curator_user: "bgd_elasticsearch1"
curator_group: "elasticsearch"
curator_version: "5.4.1"
curator_major_version: "{{ curator_version[0:1] }}.x"
curator_major_version_s: 5 
curator_rpm: "elasticsearch-curator-{{ curator_version }}.rpm"
#curator_host: {}
curator_es_hosts: {}
curator_readonlyrest_login: "curator"
curator_readonlyrest_password: "CuR4T0r"
curator_actions: {}
curator_cron_job:
  description: ""
  month: ""
  weekday: ""
  day: ""
  hour: ""
  minute: ""
  job: ""

#Cerebro
cerebro_home: "{{ admin_tools_home }}/cerebro"
cerebro_bin_dir: "{{ cerebro_home }}/bin"
cerebro_log_dir: "{{ cerebro_home }}/logs"
cerebro_pid_dir: "{{ cerebro_home }}/var/run"
cerebro_port: "1234"

cerebro_user: "bgd_elasticsearch1"
cerebro_group: "elasticsearch"
cerebro_service: "{{ cerebro_user }}_cerebro"
cerebro_version: "0.7.2"
cerebro_tarball: "cerebro-{{ cerebro_version }}.tar.gz"

