---
# Prepare Elasticsearch environment
- name: create root path
  file:
    path: "/appl"
    state: directory
    owner: "root"
    group: "root"

- name: Create elasticsearch group
  group:
    name: "{{ es_group }}"
    state: present

- name: Create nagios group
  group:
    name: "{{ nagios_group }}"
    state: present

- name: Create es_user
  user:
    name: "{{ es_user }}"
    group: "{{ es_group }}"
    home: "/appl/{{ es_user }}"

- name: Create supervision user
  user:
    name: "{{ nagios_user }}"
    group: "{{ nagios_group }}"
    home: "/appl/{{ nagios_user }}"


- name: Ensure {{ es_user_home }} path exist
  file:
    path: "{{ es_user_home }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"

- name: Ensure {{ es_user_home }}/admin/nagios path exist
  file:
    path: "{{ es_user_home }}/admin/nagios"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0775

- name: Ensure {{ es_user_home }}/admin/nagios/log path exist
  file:
    path: "{{ es_user_home }}/admin/nagios/log"
    state: directory
    owner: "{{ nagios_user }}"
    group: "{{ nagios_group }}"
    mode: 0775


